name: ci

on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master
  schedule:
    - cron:  '45 4 * * *'

jobs:
  platforms:
    strategy:
      matrix:
        os: [ubuntu, macos, windows]
        ruby: ['2.5']
    runs-on: ${{ matrix.os }}-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
      - run: bundle install
      - run: bundle exec rake
  rubies:
    strategy:
      matrix:
        os: [ubuntu]
        ruby: ['2.3', '2.4', '2.5', '2.6', '2.7', '3.0', 'ruby-head', 'debug']
    runs-on: ${{ matrix.os }}-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
      - run: bundle install
      - run: bundle exec rake

  psych4:
    strategy:
      matrix:
        os: [ubuntu]
        ruby: ['3.0']
    runs-on: ${{ matrix.os }}-latest
    env:
      PSYCH_4: "1"
    steps:
      - uses: actions/checkout@v2
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
      - run: bundle install
      - run: bundle exec rake
    

  minimal:
    strategy:
      matrix:
        os: [ubuntu]
        ruby: ['jruby', 'truffleruby']
    runs-on: ${{ matrix.os }}-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
      - run: bundle install
      - run: bin/test-minimal-support
